export const orders = [
  {
    id: "ORD-20481",
    vendor: "Spice Garden",
    vendorLogo: "🍛",
    vendorCategory: "Indian",
    status: "delivered",
    placedAt: "2025-06-02T14:30:00",
    deliveredAt: "2025-06-02T15:18:00",
    items: [
      { name: "Butter Chicken", qty: 1, price: 320 },
      { name: "Garlic Naan (x3)", qty: 3, price: 60 },
      { name: "Dal Makhani", qty: 1, price: 240 },
      { name: "Mango Lassi", qty: 2, price: 80 },
    ],
    subtotal: 780,
    deliveryFee: 40,
    discount: 78,
    total: 742,
    address: "12, Mahatma Nagar, Nashik",
    paymentMethod: "UPI",
    rating: 5,
  },
  {
    id: "ORD-20477",
    vendor: "Burger Barn",
    vendorLogo: "🍔",
    vendorCategory: "Fast Food",
    status: "out_for_delivery",
    placedAt: "2025-06-03T12:10:00",
    deliveredAt: null,
    estimatedDelivery: "2025-06-03T12:55:00",
    items: [
      { name: "Double Smash Burger", qty: 2, price: 350 },
      { name: "Loaded Fries", qty: 1, price: 180 },
      { name: "Chocolate Shake", qty: 2, price: 150 },
    ],
    subtotal: 1180,
    deliveryFee: 49,
    discount: 0,
    total: 1229,
    address: "12, Mahatma Nagar, Nashik",
    paymentMethod: "Credit Card",
    rating: null,
  },
  {
    id: "ORD-20469",
    vendor: "Wrap & Roll",
    vendorLogo: "🌯",
    vendorCategory: "Wraps & Rolls",
    status: "cancelled",
    placedAt: "2025-06-01T19:45:00",
    deliveredAt: null,
    cancelledAt: "2025-06-01T19:52:00",
    cancelReason: "Restaurant closed",
    items: [
      { name: "Paneer Tikka Wrap", qty: 2, price: 220 },
      { name: "Mint Chutney Dip", qty: 1, price: 30 },
    ],
    subtotal: 470,
    deliveryFee: 30,
    discount: 0,
    total: 500,
    address: "12, Mahatma Nagar, Nashik",
    paymentMethod: "UPI",
    rating: null,
  },
  {
    id: "ORD-20455",
    vendor: "The Pizza Co.",
    vendorLogo: "🍕",
    vendorCategory: "Pizza",
    status: "delivered",
    placedAt: "2025-05-29T20:00:00",
    deliveredAt: "2025-05-29T20:42:00",
    items: [
      { name: "Margherita (Medium)", qty: 1, price: 399 },
      { name: "Farmhouse (Large)", qty: 1, price: 599 },
      { name: "Garlic Bread Sticks", qty: 1, price: 149 },
      { name: "Pepsi (500ml)", qty: 2, price: 60 },
    ],
    subtotal: 1267,
    deliveryFee: 0,
    discount: 150,
    total: 1117,
    address: "12, Mahatma Nagar, Nashik",
    paymentMethod: "Swegi Pay",
    rating: 4,
  },
  {
    id: "ORD-20441",
    vendor: "Sushi Nori",
    vendorLogo: "🍣",
    vendorCategory: "Japanese",
    status: "delivered",
    placedAt: "2025-05-25T13:15:00",
    deliveredAt: "2025-05-25T14:05:00",
    items: [
      { name: "Dragon Roll (8 pcs)", qty: 1, price: 680 },
      { name: "Miso Soup", qty: 2, price: 120 },
      { name: "Edamame", qty: 1, price: 180 },
    ],
    subtotal: 1100,
    deliveryFee: 60,
    discount: 0,
    total: 1160,
    address: "12, Mahatma Nagar, Nashik",
    paymentMethod: "Credit Card",
    rating: 4,
  },
  {
    id: "ORD-20422",
    vendor: "Chai & Snacks",
    vendorLogo: "☕",
    vendorCategory: "Beverages",
    status: "delivered",
    placedAt: "2025-05-20T08:30:00",
    deliveredAt: "2025-05-20T09:05:00",
    items: [
      { name: "Masala Chai (x4)", qty: 4, price: 40 },
      { name: "Vada Pav (x4)", qty: 4, price: 35 },
      { name: "Samosa (x6)", qty: 6, price: 25 },
    ],
    subtotal: 560,
    deliveryFee: 20,
    discount: 56,
    total: 524,
    address: "12, Mahatma Nagar, Nashik",
    paymentMethod: "Cash on Delivery",
    rating: 5,
  },
];

export const statusConfig = {
  delivered: { label: "Delivered", color: "green" },
  out_for_delivery: { label: "Out for Delivery", color: "amber" },
  preparing: { label: "Preparing", color: "blue" },
  confirmed: { label: "Confirmed", color: "blue" },
  cancelled: { label: "Cancelled", color: "red" },
};
